Added VicReg - Variance-Invariance-Covariance Regularization for SSL
keras-team/keras-io pull request #1030
Opened 2022-08-15 16:16 UTC by dewball345

This is a reupload(sorry about that). Saw that the original PR was a little hard to find so I created a new updated one.

@owenvallis approved the code but it needs @fchollet's approval to merge into main.

2022-08-18 18:17 UTC, fchollet reviewed
Thanks for the PR. I will review shortly. Question: why delete the previous example entirely?

2022-08-18 18:32 UTC, dewball345 commented
> Thanks for the PR. I will review shortly. Question: why delete the previous example entirely?

I didn't delete the previous example, at least I don't think so? I closed the original PR because it was so far back in the PR list and wasn't getting any response.

2022-08-18 19:57 UTC, fchollet commented
> I didn't delete the previous example, at least I don't think so? If you mean the barlow twins notebook, I deleted that because this PR was about VicReg(the barlow twins was accidentally carried on due to a mistake in cloning) - had a separate PR for the barlow twins notebook

The current PR appears to be deleting the Barlow Twins example from the codebase altogether. Please rebase the PR.

Also, please only include the `.py` file in the PR until the PR is approved (since we would have to regenerated the other files at that time). There should only be one file in the "modified files" tab. Thank you!

2022-08-18 20:09 UTC, dewball345 commented
> > I didn't delete the previous example, at least I don't think so? If you mean the barlow twins notebook, I deleted that because this PR was about VicReg(the barlow twins was accidentally carried on due to a mistake in cloning) - had a separate PR for the barlow twins notebook
> 
> The current PR appears to be deleting the Barlow Twins example from the codebase altogether. Please rebase the PR.
> 
> Also, please only include the `.py` file in the PR until the PR is approved (since we would have to regenerated the other files at that time). There should only be one file in the "modified files" tab. Thank you!

Thanks for catching this! Will do!

2023-08-08 21:36 UTC, sachinprasadhs commented
@dewball345 , Could you please update on this PR. Thanks!

2023-08-09 00:23 UTC, dewball345 commented
I will see what I can do, let me have a look at this today and get back to
you.

On Tue, Aug 8, 2023, 2:36 PM Sachin Prasad ***@***.***> wrote:

> @dewball345 <https://github.com/dewball345> , Could you please update on
> this PR. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/keras-team/keras-io/pull/1030#issuecomment-1670341517>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHGJKVDV4Y4XGRLVVSCLCODXUKWPLANCNFSM56SXKUDQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-09 05:56 UTC, dewball345 commented
> @dewball345 , Could you please update on this PR. Thanks!

@sachinprasadhs I really want to thank you for letting me know with regards to updates - i completely overlooked this PR and the change that was requested by @fchollet.

2023-08-09 05:56 UTC, dewball345 commented
@sachinprasadhs @fchollet I rebased the PR accordingly and it should be fine now.

2023-09-04 20:39 UTC, pcoet commented
@dewball345 I see the following request from @fchollet:

> Also, please only include the .py file in the PR until the PR is approved (since we would have to regenerate the other files at that time). There should only be one file in the "modified files" tab. Thank you!

Can you submit the `.py` file only, so that @fchollet can review?

2023-09-04 20:44 UTC, dewball345 commented
I did, the barlow twins files were files that I brought back by rebasing my PR(there were some weird git related things that occurred and the barlow twins notebooks were deleted in this PR so I had to bring them back by a rebase). Those aren't new files, I just brought them back. Only vicreg.py is the file related to vicreg.

2023-09-04 20:46 UTC, pcoet commented
Great, thanks @dewball345! I'll go ahead and assign this to @fchollet.

2023-12-23 22:54 UTC, dewball345 commented
Any update on this? @pcoet @fchollet

2024-01-02 14:37 UTC, pcoet requested changes
@dewball345 Thanks for the ping on this. I made a couple of nitty suggestions on the Markdown content. Can you make those changes, and then we'll ask @fchollet to do a review?

2024-01-02 14:37 UTC, pcoet commented on examples/vision/vicreg.py
> +like a classification model, these embeddings(which have the curated measurements
Missing space: "embeddings(which" -> "embeddings (which".

2024-01-02 14:37 UTC, pcoet commented on examples/vision/vicreg.py
> +it)](https://keras.io/examples/vision/barlow_twins/)
Markdown links have to be on a single line.

2024-01-02 14:40 UTC, pcoet commented
@dewball345 Also, I apologize for not requesting these changes earlier. Thanks for your patience!

2024-07-16 20:32 UTC, dewball345 commented
@pcoet Hi, it has been a while. I forgot about this PR for a while but I went back and made the fixes. Please have a look

2024-07-16 21:12 UTC, sachinprasadhs commented
@dewball345 , We have migrated from Keras 2 to Keras 3, could you please consider migrating this tutorial to Keras 3.
For more details visit https://keras.io/guides/migrating_to_keras_3/

2025-01-16 21:50 UTC, divyashreepathihalli commented
Closing because this PR is stale.

2025-01-16 21:50 UTC, closed without merging