Compatibility change for KerasNLP 0.4 release
keras-team/keras-io pull request #1169
Opened 2022-12-22 22:01 UTC by chenmoneygithub

2022-12-23 00:42 UTC, mattdangerw requested changes
Looks good! Just a few minor comments.

2022-12-23 00:42 UTC, mattdangerw commented on examples/nlp/fnet_classification_with_keras_nlp.py
>  def train_word_piece(ds, vocab_size, reserved_tokens):
why not just remove this whole function and just inline?

also, above this in the paragraph replace

"Luckily, TensorFlow Text
makes it very simple to train WordPiece on a corpus as described in
[this guide](https://www.tensorflow.org/text/guide/subwords_tokenizer)."

with

"We can train a WordPiece vocabulary ourselves with `keras_nlp.tokenizers.compute_word_piece_vocabulary`."

2022-12-23 00:42 UTC, mattdangerw commented on examples/nlp/neural_machine_translation_with_keras_nlp.py
Same here, above this line, replace the "Luckily" sentence with the suggestion I had above or something like it.

2022-12-23 00:42 UTC, mattdangerw commented on examples/nlp/neural_machine_translation_with_keras_nlp.py
> -have you seen this?
should we keep a few examples in? Will help readability when not running this as a colab.

2022-12-23 00:42 UTC, mattdangerw commented on guides/keras_nlp/transformer_pretraining.py
>  The second thing we need to do is mask our input for the MLM task. To do this, we can use
MLM -> MaskedLM

And rename this section "Preprocess data for the MLM task" -> "Preprocess data for the MaskedLM task"

2022-12-23 00:42 UTC, mattdangerw commented on guides/keras_nlp/transformer_pretraining.py
>  set up the encoder to train on the MLM task; to do that we attach a
MLM -> MaskedLM

2022-12-27 21:20 UTC, mattdangerw approved these changes
LGTM, just a few spurious warnings we might want to avoid rendering on keras.io

2022-12-27 21:20 UTC, mattdangerw commented on guides/md/keras_nlp/transformer_pretraining.md
> +WARNING:tensorflow:From /opt/conda/envs/myenv/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.
Can we remove these three lines, this should be fixed in upstream tensorflow shortly, and is just distracting for now.

2022-12-27 21:20 UTC, mattdangerw commented on guides/md/keras_nlp/transformer_pretraining.md
> +WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
Can we remove this large block of WARNING and INFO logs for now? Not sure what's going on here.

2022-12-28 07:04 UTC, fchollet commented
It seems there are commits from `ch*****ey​@chenmoney-gpu.c.keras-team-gcp.internal` which does not have a CLA associated with it. Please create a single commit with the changes to fix this issue.

2022-12-28 07:37 UTC, chenmoneygithub commented
@fchollet Commits from GCP compute engine all have this weird CLA issue, and I cannot find a way to sign it. Is this issue blocking? I need to run the generation script from GCP because it takes a few hours on my outdated GPU. 

If this is blocking, maybe we can do the review and address comments first, then squashing all commits outside GCP, so I don't need to run the generation script?

2022-12-28 16:44 UTC, fchollet commented
It seems I'm actually able to merge without the CLA. Let me try that.

Otherwise the fix would have been to do a clean commit locally. This can be done after committing files from the GCP instance.

> Commits from GCP compute engine all have this weird CLA issue

In the future, all you need is to configure `git` locally on the GCP instance so that it uses your regular email address. You can do so via `git config --global user.email "chenmoney@google.com"`

2022-12-28 16:44 UTC, merged