Create keras_issue_template.yaml
keras-team/keras-io pull request #1385
Opened 2023-05-24 20:22 UTC by sachinprasadhs

2023-08-11 18:22 UTC, sachinprasadhs commented
@MarkDaoust , Could you please review and let me know if any changes are required. Thanks!

2023-10-31 06:40 UTC, gbaned commented
Hi @MarkDaoust, Can you please review this PR ? Thank you!

2023-11-15 20:44 UTC, pcoet requested changes

2023-11-15 20:44 UTC, pcoet commented on .github/ISSUE_TEMPLATE/keras_issue_template.yaml
> +      description: Tensorflow/Keras installed from
"Tensorflow" -> "TensorFlow"

2023-11-15 20:44 UTC, pcoet commented on .github/ISSUE_TEMPLATE/keras_issue_template.yaml
> +    id: Gpu
`Gpu` -> `GPU` or `gpu`

2023-11-15 22:10 UTC, sachinprasadhs commented
Made suggested changes, you can preview it here https://github.com/sachinprasadhs/keras-io/blob/patch-2/.github/ISSUE_TEMPLATE/keras_issue_template.yaml

2023-11-15 23:28 UTC, pcoet approved these changes

2023-11-15 23:28 UTC, merged