Update encoding in movielens_recommendations_transformers.py
keras-team/keras-io pull request #1406
Opened 2023-06-20 09:47 UTC by SuryanarayanaY

At present the example tutorial raising the UnicodeDecodeError at ` movies=pd.read_csv()`

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3114: invalid continuation byte`

Hence adding the `encoding='latin-1'` to the `movies=pd.read_csv(...,encoding='latin-1')` will get rid of this error.

Hence I proposed this code change for review and approval.

2023-06-22 20:14 UTC, haifeng-jin requested changes
Thanks for the PR!
I was able to verify the bug and fix.

The only thing is the code formatting.
Would you please use `black` to format the `.py` file and also change the corresponding `.ipython` and `.md` file?

2023-07-27 09:49 UTC, SuryanarayanaY commented
All the checks passed now. May please review.

2023-10-31 06:37 UTC, gbaned commented
Hi @haifeng-jin, Can you please review this PR ? Thank you!

2023-11-28 18:53 UTC, haifeng-jin reviewed
By looking at the conflicts of the PR, the bug seems already been patched with an ISO encoding. Would you please check again while resolving the conflicts? Thanks!

2023-12-16 04:28 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @haifeng-jin's comments and keep us posted ? Thank you!

2024-01-08 12:51 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2024-01-11 22:31 UTC, sachinprasadhs commented
Closing the PR, since the tutorial is already migrated and working fine with the Keras 3 using ISO encoding here https://keras.io/examples/structured_data/movielens_recommendations_transformers/

2024-01-11 22:31 UTC, closed without merging