add Approximating non function mapping example
keras-team/keras-io pull request #1440
Opened 2023-07-16 03:25 UTC by LukeWood

2023-08-04 17:18 UTC, MarkDaoust requested changes
I put a bunch of fixes in this PR:

https://github.com/LukeWood/keras-io/pull/2, Please merge, lgtm.

I wasn't able to push it directly to your branch. 

Do new files need to be added to index pages for keras.io?

2023-08-07 19:43 UTC, LukeWood commented on examples/keras_recipes/approximating_non_function_mappings.py
> +One important restriction to remember about functions - they have one input, one
Perhaps...

One important characteristic of functions is that they map one input to a one unique output.
Neural networks suffer greatly when the training set has multiple values of Y for a single X.

2023-08-07 19:44 UTC, LukeWood commented on examples/keras_recipes/approximating_non_function_mappings.py
> +respect to geometric space.
However, in the context of our spiral the geometric mean of the each Y occurs with a probability of zero...

2023-08-07 19:45 UTC, LukeWood commented on examples/keras_recipes/approximating_non_function_mappings.py
> +A Mixture density is a class of complicated densities expressible in terms of simpler densities.
Mixture density -> mixture density

2023-08-07 19:46 UTC, LukeWood commented on examples/keras_recipes/approximating_non_function_mappings.py
> +They are effectively the sum of a ton of probability distributions.
effectively, a mixture density is the sum of various probability distributions.  By summing various distributions, mixture densitry distributions can effectively model arbitrarily complex distributions.

2023-08-07 19:46 UTC, LukeWood reviewed
@fchollet I think this looks pretty good - @MarkDaoust added some edits.

I left a few final copy-edits on my own wording which I can apply later today - but let me know if this is a good addition.

Edit: sorry, misunderstood Mark's comment.  Merged his PR on my repo.

2023-08-08 03:01 UTC, LukeWood commented
@MarkDaoust I merged them - let me know if anything else is needed!

2023-08-08 03:02 UTC, LukeWood commented
FYI @MarkDaoust you may want to re-generate the markdown, the learned MDN is pretty poor here - and I've been able to get much stronger convergences.  Maybe we can just run it 1-2 more times to get good figures

2023-08-08 20:24 UTC, MarkDaoust approved these changes
LGTM.

2023-08-08 20:41 UTC, MarkDaoust commented
@LukeWood did you want to add those copy edits and regenerate, or should I just merge this?

2023-08-08 22:13 UTC, LukeWood commented
Go ahead @MarkDaoust - I think the point is still clear and I'm happy with it.  Cheers!

2023-08-11 16:48 UTC, merged