Port sentence embedding example to keras-core
keras-team/keras-io pull request #1473
Opened 2023-08-08 21:25 UTC by abuelnasr0

Port sentence embedding example to keras-core. keras-team/keras-nlp#1190
I will generate other files and add them once these changes get accepted. 
@mattdangerw

2023-08-09 16:52 UTC, MarkDaoust commented
Hi, thanks for the PR. We really appreciate it when authors maintain their examples.

I have one question about this change: 

It adds +175 lines, but at first glance it feels like most of the added lines are packing and repacking dictionaries that weren't necessary before.

Is the upgrade to keras-core forcing you to do this, or is it purely driven by the decision to move the text-preprocessing into the `tf.data.Dataset`? (I assume keras tensor-masks don't make it through). I know that can be good from an accelerator efficiency POV, but these examples should  be short and readable.

2023-08-10 19:43 UTC, abuelnasr0 commented
@MarkDaoust Torch and jax doesn't have string dtype. so I was forced to move text-preprocessing to tf.data.Dataset. I will try to make it shorter.

2023-08-11 16:28 UTC, MarkDaoust requested changes
That's too bad.  One of the things I love about the old approach is that you can export the model with all it's preprocessing, so that you can just throw strings at it and don't need to worry about separately exporting and running the string processing. I wonder if it would make sense to fork so people can see both versions.

> try to make it shorter.

LMK if I'm wrong, but I think you can save a bit in all the spots where you're flattening dictionaries. keras supports nested dicts, does keras_core?

2023-08-11 16:28 UTC, MarkDaoust commented on examples/nlp/sentence_embeddings_with_sbert.py
> +        lambda x: (
Please just write this out as a stand alone function, it will be clearer.

2023-08-11 16:28 UTC, MarkDaoust commented on examples/nlp/sentence_embeddings_with_sbert.py
> +    return {
Does keras_core support nested dictionaries?

Shouldn't this work:

{'input0': x[0], 'input1':x[1]}?

2023-08-11 16:28 UTC, MarkDaoust commented on examples/nlp/sentence_embeddings_with_sbert.py
> +### Build the encoder model.
I think this section made more sense where it was, in logical order:
- Convert text to tokens.
- Encode the tokens.

2023-08-26 16:33 UTC, abuelnasr0 commented
@MarkDaoust sorry for late reply. I think forking will be great. I have seen that in keras_core library there is an example folder where a lot of TF examples are being ported into keras_core. so I can add this example there ? or should I create new version of it here?

>  keras supports nested dicts, does keras_core?

keras_core doesn't support that unfortunately.
I think adding the example in keras_core/examples would make sense more. if it is better to add it here I will create a new file with keras_core example.

2023-09-24 01:45 UTC, closed without merging