Fixing the comment line where the sequence length about the dataset was incorrect.
keras-team/keras-io pull request #549
Opened 2021-07-16 07:53 UTC by jorgpg5

The FordA sequences length value is 500 instead of 176. This situation can be seen in the jupyter notebook and the .py file.

According to the paper and the code, the sequences length value is 500 instead of 176. I know that this is a minor detail, but it might be important to have that value correct for learning purposes.

![image](https://user-images.githubusercontent.com/70129680/125911640-213bd53a-2010-4015-9968-c054b7ffbe0e.png)

Page 92 [Source](https://www.cs.ucr.edu/~eamonn/time_series_data_2018/BriefingDocument2018.pdf)
![image](https://user-images.githubusercontent.com/70129680/125911736-baa9d03a-75f7-47f1-9997-4aea1fdfcf52.png)

[Source](http://www.j-wichard.de/publications/FordPaper.pdf)
![image](https://user-images.githubusercontent.com/70129680/125912411-f21d565d-6212-41cc-880a-5396dadfa15c.png)

2021-07-16 07:55 UTC, jorgpg5 commented
@googlebot I signed it!

2021-07-17 23:16 UTC, fchollet requested changes
Thanks for the PR. Please also modify the `.md` file.

2021-07-19 02:38 UTC, jorgpg5 commented
Thanks, @fchollet. Sorry about that. I totally forgot about the .md file. Now it's done. 

Thank you!

2021-07-19 05:50 UTC, fchollet approved these changes

2021-07-19 05:50 UTC, merged