Added HuggingFace links for CCT and Timeseries classification from scratch
keras-team/keras-io pull request #955
Opened 2022-06-30 21:08 UTC by EdAbati

As part of the HuggingFace Keras sprint, I have added the HF links in the CCT and the Timeseries classification from scratch examples.

2023-08-16 12:31 UTC, pcoet commented
@EdAbati Thanks for the PR. It looks like one of the checks failed, and unfortunately the log has expired so I can't investigate. Are you still working on this? Please let us know. Otherwise we'll close the request. Thanks!

2023-08-16 13:21 UTC, EdAbati commented
Hi @pcoet , I forgot about this one. :) Happy to have a look at it

2023-08-19 09:59 UTC, EdAbati commented
Hi @pcoet , I have updated the branch with master and it looks like this did the trick!

2023-08-19 13:16 UTC, pcoet requested changes
I'm seeing one formatting issue when I look at these new links in a notebook. Can you fix?

2023-08-19 13:16 UTC, pcoet commented on examples/timeseries/timeseries_classification_from_scratch.py
> +Example available on HuggingFace:
I think that you need a break between the intro sentence (`Example available on HuggingFace:`) and the table, to make the formatting work. Can you add that and regenerate?

2023-08-19 13:16 UTC, pcoet commented on examples/vision/cct.py
> +Example available on HuggingFace:
See previous comment. I think you need a return between the intro text and the table to make the link table render correctly. That's what I'm seeing in the notebook. Can you add that and regenerate?

2023-08-21 13:34 UTC, pcoet approved these changes

2023-08-21 13:35 UTC, merged