Open Ended Text Generation Guide KerasNLP
keras-team/keras-io pull request #956
Opened 2022-07-01 12:14 UTC by aflah02

This guide compares byte and unicode tokenizers for text generation
@mattdangerw Raised a PR based on our discussion
Referring to the README, I will add the generated files after approval.
Reference: https://github.com/keras-team/keras-nlp/issues/191

2022-07-07 16:59 UTC, fchollet reviewed
Thanks for the PR! Some preliminary comments for now.

@mattdangerw please take a look at the example as well.

2022-07-08 04:51 UTC, mattdangerw requested changes
Thanks! Left some initial comments

2022-07-08 04:51 UTC, mattdangerw commented on examples/nlp/character_and_byte_level_text_generation.py
> +We can see post tokenization the datasets now differ which is to be expected as byte tokenization and unicode
maybe just phrase this as

Let's try tokenizing the the input string "señora mía".

print(codepoint_tokenizer("señora mía))
print(byte_tokenizer("señora mía))

This captures the tradeoff between the two tokenizer. The byte tokenizer will handle any text with only 256 output ids, at the cost of encoding to a longer sequence. The unicode tokenizer will produce shorted sequence, at the cost of a larger id space (and larger embeddings).

2022-07-08 04:51 UTC, mattdangerw commented on examples/nlp/character_and_byte_level_text_generation.py
> +OUTPUT:   que ya su dulce esposo no vivía, rompió los aires con suspiros, hirió los cielos con quejas, maltra de su don quijoteâ, que su perreso de su cab
We need to keep looking at where these erroneous characters are coming from `â`, maybe we need a longer dataset? Different hyperparameters? Maybe trying the transfomer will help?

Especially with greed search, we should at least be able to train to the point where we output a valid set of characters that are actually in the source text.

2022-07-12 07:39 UTC, aflah02 commented on examples/nlp/character_and_byte_level_text_generation.py
> +Let's do our imports first
Got it!

2023-08-17 06:46 UTC, aflah02 commented
@pcoet Sorry I'm blocked due to other commitments and would be unable to finish this PR in the near future. Closing it for now then

2023-08-17 06:46 UTC, closed without merging